/**
 * Bundles the frontend (src/index.html + main.tsx) into a single HTML file
 * and emits src/frontend.generated.ts exporting it as FRONTEND_HTML.
 *
 * Run with: bun scripts/build-frontend.ts
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT_DIR = join(ROOT, "dist-web");
const OUT_TS = join(ROOT, "src", "frontend.generated.ts");

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const result = await Bun.build({
	entrypoints: [join(ROOT, "src", "index.html")],
	outdir: OUT_DIR,
	target: "browser",
	minify: true,
});

if (!result.success) {
	for (const log of result.logs) console.error(log);
	process.exit(1);
}

const entries = await readdir(OUT_DIR);
let html = await readFile(join(OUT_DIR, "index.html"), "utf8");

// Inline every local script (src="/index-*.js") into the HTML so the whole
// frontend ships as a single embeddable document.
const scriptRe = /<script type="module" crossorigin src="\.\/([^"]+)"><\/script>|<script type="module" src="\.\/([^"]+)"><\/script>/g;
const matches = [...html.matchAll(scriptRe)];
for (const m of matches) {
	const file = m[1] ?? m[2];
	if (!file || !entries.includes(file)) continue;
	const js = await readFile(join(OUT_DIR, file), "utf8");
	// Avoid breaking out of the inline script context.
	const safe = js.replaceAll("</script", "<\\/script");
	// Use a replacer function: the minified bundle contains `$&`, `$'`, etc.,
	// which String.replace would otherwise interpret as replacement patterns.
	html = html.replace(m[0], () => `<script type="module">${safe}</script>`);
}

const header = `// Generated by scripts/build-frontend.ts — do not edit.
export const FRONTEND_HTML = `;

await writeFile(OUT_TS, header + JSON.stringify(html) + ";\n");
console.log(`Wrote ${OUT_TS} (${html.length} bytes of HTML)`);
